sudo: required
services:
  - docker

before_install:
  - docker build -t alfonsohooker/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true alfonsohooker/docker-react npm run test
deploy:
  edge: true 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: test-react
  env: "TestReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-967195537723"
  bucket_path: "test-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
